name: bee_app
description: "A beekeeping management app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.22.1
  sqlite3_flutter_libs: ^0.5.28
  path_provider: ^2.1.5
  path: ^1.9.1
  provider: ^6.1.2
  go_router: ^14.8.1
  http: ^1.3.0
  shared_preferences: ^2.3.5
  uuid: ^4.5.1
  intl: ^0.19.0
  speech_to_text: ^7.0.0
  connectivity_plus: ^6.1.3
  image_picker: ^1.1.2
  flutter_local_notifications: ^18.0.1
  json_annotation: ^4.9.0
  url_launcher: ^6.3.1
  socket_io_client: ^3.0.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.22.1
  build_runner: ^2.4.14
  json_serializable: ^6.9.4
  mockito: ^5.4.5
  build_verify: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
